best_class_weight: balanced
best_colsample_bytree: '0.9'
best_learning_rate: '0.01'
best_max_depth: '6'
best_min_child_samples: '50'
best_n_estimators: '400'
best_num_leaves: '15'
best_reg_alpha: '0.1'
best_reg_lambda: '2.0'
best_scale_pos_weight: '20'
best_search_scoring: f1
best_search_value: '1.0'
best_subsample: '0.8'
n_features: '17'
n_iter: '64'
random_state: '42'
scoring: f1
search_type: randomized
test_size: '0.2'
