model_quality:
  min_accuracy: 0.35
  min_f1: 0.50

'lgb.LGBMClassifier':
  target: has_malnutrition
  test_size: 0.2
  random_state: 42
  n_estimators: 100
  max_depth: 10
  learning_rate: 0.1
  random_seed: 42
  class_weight: 'balanced'

# ---------------------------------------
# Setup for random grid CV 
# ----------------------------------------

model: lgb.LGBMClassifier

target: has_malnutrition

split:
  type: stratified_kfold
  n_splits: 5
  shuffle: true
  random_state: 42

search:
  type: randomized
  n_iter: 40
  scoring: f1
  n_jobs: -1
  verbose: 1
  random_state: 42

param_distributions:
  n_estimators: [100, 200, 300, 400, 500]
  learning_rate: [0.01, 0.03, 0.05, 0.1]
  max_depth: [-1, 4, 6, 8, 10]
  num_leaves: [15, 31, 63, 127]
  min_child_samples: [5, 10, 20, 30, 50]
  subsample: [0.6, 0.7, 0.8, 0.9, 1.0]
  colsample_bytree: [0.6, 0.7, 0.8, 0.9, 1.0]
  reg_alpha: [0, 0.1, 0.5, 1.0]
  reg_lambda: [0, 0.5, 1.0, 2.0]

  # Try ONE of these strategies at a time ideally
  class_weight: [null, 'balanced']
  scale_pos_weight: [10, 15, 20]

fit_params:
  eval_metric: recall
